name: test run one
on: push
jobs:
  actual-job:
    runs-on: ubuntu-latest
    steps:
      - name: fail
        run: exit 1
  final-job:
    runs-on: ubuntu-latest
    needs: [actual-job]
    steps:
      - name: final
        run: echo "final"
  report-job:
    runs-on: ubuntu-latest
    needs: [final-job]
    if: github.action_status == 'failure' || github.action_status == 'success'
    steps:
      - name: slack
        run: |
           echo "success ${{github.action_status}} ${{job.status}}"
           
