name: test run one
on: push
jobs:
  success-job:
    runs-on: ubuntu-latest
    steps:
      - name: hi
        run: echo "Hi"
      - name: fail
        run: exit 1
      - name: slack success
        if: always()
        run: echo "slack ${{job.status}}"
