name: test run one
on: push
jobs:
  actual-job:
    runs-on: ubuntu-latest
    steps:
      - name: Set Github environment variables
        uses: ScientaNL/github-actions-env-toolkit@main
           
