name: test run one
on: push
jobs:
  actual-job:
    runs-on: ubuntu-latest
    steps:
      - name: hi
        run: echo "Hi"
      - name: fail
        run: exit 1
      - name: slack
        if: always()
        run: echo "slack ${{job.status}}"
  final-job:
    runs-on: ubuntu-latest
    needs: [actual-job]
    steps:
      - run: echo "final job"
  report-job:
    runs-on: ubuntu-latest
    needs: [actual-job, final-job]
    if: always()
    steps:
      - name: failure?
        if: failure()
        run: echo "failure"
      - name: slack
        run: |
           STATUSES="${{join(needs.*.result,'')}}" # Combines all results in one long string
           echo "statuses: $STATUSES"
           FILTERED="${STATUSES//success/}" # Removes all success statuses
           echo "filtered: $FILTERED"
           STATUS=$([[ -z "$FILTERED" ]] && echo "success" || echo "failure") # if not empty, its a failure
           echo "status: $STATUS"
#          echo "slack ${{job.status}}"
#          echo "${{toJSON(github)}}"
#          echo "${{needs.actual-job.result == 'success' && 'succ' || 'fail'}}"
#          echo "gas ${{github.action_status}}"
