name: test run one
on: push
jobs:
  actual-job:
    runs-on: ubuntu-latest
    steps:
      - name: hi
        run: echo "Hi"
      - name: fail
        run: exit 0
      - name: slack
        if: always()
        run: echo "slack ${{job.status}}"
  report-job:
    runs-on: ubuntu-latest
    needs: [actual-job]
    if: always()
    steps:
      - name: slack
        run: |
           echo "${{toJSON(needs)}}"
           echo "${{toJSON(needs.actual-job)}}"
           echo "${{toJSON(needs.*.result)}}"
           echo "${{toJSON(failure())}}"
           echo "${{toJSON(success())}}"
#          echo "slack ${{job.status}}"
#          echo "${{toJSON(github)}}"
#          echo "${{needs.actual-job.result == 'success' && 'succ' || 'fail'}}"
#          echo "gas ${{github.action_status}}"
