name: test run one
on: push
jobs:
  actual-job:
    runs-on: ubuntu-latest
    steps:
      - name: fail
        run: exit 1
  final-job:
    runs-on: ubuntu-latest
    needs: [actual-job]
    steps:
      - name: final
        run: echo "final"
  report-job-success:
    runs-on: ubuntu-latest
    needs: [final-job]
    if: success()
    steps:
      - name: slack
        run: |
           echo "success"
  report-job-failure:
    runs-on: ubuntu-latest
    needs: [final-job]
    if: failure()
    steps:
      - name: slack
        run: |
           echo "failure"
           
