name: test run one
on: push
jobs:
  actual-job:
    runs-on: ubuntu-latest
    steps:
      - name: hi
        run: echo "Hi"
      - name: fail
        run: exit 0
      - name: slack
        if: always()
        run: echo "slack ${{job.status}}"
  report-job:
    runs-on: ubuntu-latest
    needs: [actual-job]
    if: always()
    steps:
      - name: slack
        run: |
           echo "${{toJSON(needs)}}"
           echo "${{toJSON(needs.actual-job)}}"
           echo "${{toJSON(needs.*.result)}}"
           CONCAT_RESULTS="${{join(needs.*.result,'')}}"
           echo "$CONCAT_RESULTS"
           FILTERED="${CONCAT_RESULTS//success/}"
           echo "$FILTERED"
           STATUS=$([[ -z "$FILTERED" ]] && echo "success" || echo "failure")
           echo "$STATUS"
#          echo "slack ${{job.status}}"
#          echo "${{toJSON(github)}}"
#          echo "${{needs.actual-job.result == 'success' && 'succ' || 'fail'}}"
#          echo "gas ${{github.action_status}}"
