name: test run one
on: push
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Say hi, as step
        run: echo "Hi, from a step"
        shell: bash
      - name: run one
        uses: ./action-one
